backend:
  name: wanderlust-backend
  serviceName: backend-svc
  replicas: 2
  app: backend
  image: 940521993730.dkr.ecr.us-east-1.amazonaws.com/wanderlust-backend
  tag: v1
  imagePullPolicy: Always
  port: 5000
  targetPort: 5000
  nodeport: 30001
  path: /

  jwtSecret: "MySuperSecretKey123"

frontend:
  name: wanderlust-frontend
  serviceName: frontend-svc
  replicas: 2
  app: frontend
  image: 940521993730.dkr.ecr.us-east-1.amazonaws.com/wanderlust-frontend
  port: 80
  nodeport: 30000
  path: /
  targetPort: 80
  tag: v1
  imagePullPolicy: Always

mongodb:
  name: mongodb
  namespace: wanderlust
  serviceName: mongodb-sc
  app: mongodb
  replicas: 2

  image: mongo:7.0
  pullPolicy: IfNotPresent

  port: 27017
  dbName: wanderlust

  storageClassName: gp2

  storage:
    size: 1Gi

secret:
  name: mongodb-secret
  namespace: wanderlust
  jwtSecret: mysecretkey
  mongoUser: YWRtaW4=
  mongoPassword: c2VjcmV0MTIz

namespace:
  name: wanderlust


redis:
  name: redis
  namespace: wanderlust
  app: redis
  serviceName: redis
  replicas: 1
  image: redis:7 # matched to your docker-compose
  pullPolicy: IfNotPresent
  port: 6379
  storageClassName: gp2
  storageSize: 512Mi



ingress:
  enabled: true
  name: wanderlust-ingress
  namespace: wanderlust
  ingressClassName: alb

  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'




