backend:
  name: wanderlust-backend
  replicas: 2
  app: backend
  image: 940521993730.dkr.ecr.us-east-1.amazonaws.com/wanderlust-backend
  port: 5000
  nodeport: 30001
  path: /backend/health
  targetPort: 5000
  tag: v1
  imagePullPolicy: Always

frontend:
  name: wanderlust-frontend
  replicas: 2
  app: frontend
  image: 940521993730.dkr.ecr.us-east-1.amazonaws.com/wanderlust-frontend
  port: 80
  nodeport: 30000
  path: /
  targetPort: 80
  tag: v1
  imagePullPolicy: Always

mongodb:
  name: mongodb
  dbName: wanderlust
  serviceName: mongodb-sc
  namespace: wanderlust
  replicas: 2
  app: mongodb
  image: mongo:7.0
  port: 27017
  database: starbucks
  storageClassName: standard
  secretName: mongodb-secret
  pullPolicy: IfNotPresent # Kind built-in storage class
  storage:
    size: 1Gi

secret:
  name: mongodb-secret
  jwtSecret: mysecretkey
  mongoUser: YWRtaW4=
  mongoPassword: c2VjcmV0MTIz

namespace:
  name: wanderlust

redis:
  name: redis
  namespace: wanderlust
  app: redis
  serviceName: redis
  replicas: 1
  image: redis:7 # matched to your docker-compose
  pullPolicy: IfNotPresent
  port: 6379
  storageClassName: standard
  storageSize: 512Mi


ingress:
  enabled: true
  name: wanderlust-ingress
  namespace: wanderlust
  ingressClassName: alb

  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: project-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

ArgoCD:
  name: argocd-ingress
  namespace: argocd
  serviceName: argocd-server 
  port:
    number: 80

grafana:
  name: grafana-ingress
  namespace: prometheus
  serviceName: kube-prometheus-stack-grafana
  port: 80


ServiceAccount:
  serviceAccountName: aws-load-balancer-controller
  namespace: kube-system

  annotations:
    eksRoleArn: arn:aws:iam::940521993730:role/eks-ingress