apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  JWT_SECRET: mysecretkey

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  mongo-root-username: {{.Values.secret.mongoUser | b64enc }}
  mongo-root-password: {{.Values.secret.mongoPassword | b64enc }}