apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ArgoCD.name }}
  namespace: {{ .Values.ArgoCD.namespace }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ArgoCD.serviceName }}
                port:
                  number: {{ .Values.ArgoCD.port.number }}