apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.configmap.namespace }}

data:
  PORT: "5000"
  MONGODB_URI: "mongodb://{{ .Values.mongodb.serviceName }}:27017/wanderlust"
