apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.backend.jwtSecret | quote }}
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mongo-root-username: {{ .Values.secret.mongoRootUsername | quote }}
  mongo-root-password: {{ .Values.secret.mongoRootPassword | quote }}