apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  mongo-root-username: {{ .Values.secret.mongoUser | b64enc }}
  mongo-root-password: {{ .Values.secret.mongoPassword | b64enc }}